In [1]:
!mamba install pandas

mambajs 0.21.4

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 2.998 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.6    np23py313h124dbc7_0  emscripten-forge-4x
+ python-tzdata  2026.3   pyhd8ed1ab_0         conda-forge
- pip            26.2.1   pyh145f28c_0         conda-forge

In [9]:
import pandas as pd
data = { 'apples' :[3,2,0,1] , 'oranges':[0,3,7,2] }
df = pd.DataFrame(data, index=['Ahmad', 'Ali', 'Rashed', 'Hamza'])
print(df)
df.loc['Ali']

        apples  oranges
Ahmad        3        0
Ali          2        3
Rashed       0        7
Hamza        1        2

apples     2
oranges    3
Name: Ali, dtype: int64

In [17]:
import pandas as pd
df = pd.read_csv('Iris (1).csv')
print(df)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]

In [18]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [19]:
df.head(2)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa

In [20]:
df.head(4)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 6.5 KB

In [23]:
df.shape

(150, 6)

In [28]:
import pandas as pd

df = pd.read_json("sample1.json", typ="series")
print(df)

fruit    Apple
size     Large
color      Red
dtype: str

In [35]:
import pandas as pd
df = pd.read_csv('Iris (1).csv')
df.shape
dup_df= pd.concat([df,df])
dup_df.shape
print(dup_df)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[300 rows x 6 columns]

In [36]:
dup_df.drop_duplicates(inplace =True)
dup_df.shape

(150, 6)

In [37]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [38]:
import pandas as pd
data = [1,2,3,10,20,30]
df = pd.DataFrame(data)
print(df)

    0
0   1
1   2
2   3
3  10
4  20
5  30

In [39]:
df.to_csv('Z.csv')

In [40]:
data = {'col_1':[3,2,1,0], 'col_2':['a','b','c','d']}
pd.DataFrame.from_dict(data)

   col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d

In [48]:
import pandas as pd

data = {
    "Student Roll No": [1,2,3,4,5,6,7,8,9,10],
    "Student Age": [19,18,18,20,21,22,23,24,25,26],
    "Section": ["A","B","C","D","E","F","G","H","I","J"],
    "TOC": [100,100,89,85,89,95,59,68,90,99],
    "DS": [100,95,56,80,83,94,60,69,76,100],
    "ASE": [90,99,85,86,87,98,58,89,45,83]
}

df = pd.DataFrame(data)
df.to_csv("students.csv")
print(df)

   Student Roll No  Student Age Section  TOC   DS  ASE
0                1           19       A  100  100   90
1                2           18       B  100   95   99
2                3           18       C   89   56   85
3                4           20       D   85   80   86
4                5           21       E   89   83   87
5                6           22       F   95   94   98
6                7           23       G   59   60   58
7                8           24       H   68   69   89
8                9           25       I   90   76   45
9               10           26       J   99  100   83

In [46]:
import pandas as pd

df = pd.read_csv("students.csv")
print(df)

   Student Roll No  Student Age Section  TOC   DS  ASE
0                1           19       A  100  100   90
1                2           18       B  100   95   99
2                3           18       C   89   56   85
3                4           20       D   85   80   86
4                5           21       E   89   83   87
5                6           22       F   95   94   98
6                7           23       G   59   60   58
7                8           24       H   68   69   89
8                9           25       I   90   76   45
9               10           26       J   99  100   83

In [47]:
df.tail()

   Student Roll No  Student Age Section  TOC   DS  ASE
5                6           22       F   95   94   98
6                7           23       G   59   60   58
7                8           24       H   68   69   89
8                9           25       I   90   76   45
9               10           26       J   99  100   83

In [49]:
df.head()

   Student Roll No  Student Age Section  TOC   DS  ASE
0                1           19       A  100  100   90
1                2           18       B  100   95   99
2                3           18       C   89   56   85
3                4           20       D   85   80   86
4                5           21       E   89   83   87